version: '3.9'

services:
  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: medico

volumes:
  -psql-data:
