version: '3.9'

services:
  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: medico

  minio:
    image: 'minio/minio:latest'
    ports:
      - "6000:6000"
      - "8700:8700"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio:/data/minio
    command: 'minio server /data/minio --console-address ":8700"'

volumes:
  -psql-data:
  minio:
    driver: local

